/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminStats {
  'totalOrders' : bigint,
  'totalInstruments' : bigint,
  'totalUsers' : bigint,
}
export interface AppSettings {
  'privacyText' : string,
  'termsText' : string,
  'stockLossColor' : string,
  'stockGainColor' : string,
}
export type Category = { 'forex' : null } |
  { 'stock' : null } |
  { 'crypto' : null } |
  { 'commodity' : null };
export type CreditCodeStatus = { 'active' : null } |
  { 'redeemed' : null };
export interface CreditCodeV2 {
  'redeemedAt' : [] | [Time],
  'redeemedBy' : [] | [string],
  'status' : CreditCodeStatus,
  'code' : string,
  'createdAt' : Time,
  'amount' : number,
}
export interface DepositRequestV2 {
  'id' : string,
  'status' : DepositStatus,
  'userEmail' : string,
  'utrNumber' : [] | [string],
  'amount' : number,
  'requestTime' : Time,
}
export type DepositStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Instrument {
  'currentPrice' : number,
  'name' : string,
  'previousClose' : number,
  'priceChangePercent' : number,
  'category' : Category,
  'symbol' : string,
}
export interface InstrumentUpdate {
  'currentPrice' : number,
  'previousClose' : number,
  'symbol' : string,
}
export type OrderStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'rejected' : null } |
  { 'executed' : null };
export type OrderType = { 'limit' : null } |
  { 'stopLoss' : null } |
  { 'market' : null };
export interface OrderV2 {
  'id' : string,
  'status' : OrderStatus,
  'userEmail' : string,
  'tradeType' : TradeType,
  'side' : Side,
  'orderType' : OrderType,
  'marginUsed' : number,
  'timestamp' : Time,
  'quantity' : number,
  'price' : number,
  'symbol' : string,
}
export interface PaymentSettingsV2 {
  'bankAccountNumber' : string,
  'qrCodeData' : string,
  'bankAccountHolder' : string,
  'bankIfsc' : string,
  'bankName' : string,
  'upiId' : string,
}
export interface PortfolioSummary {
  'totalInvested' : number,
  'availableBalance' : number,
  'marginAvailable' : number,
  'totalPnL' : number,
  'currentValue' : number,
  'marginUsed' : number,
}
export interface PositionSummary {
  'tradeType' : TradeType,
  'marginUsed' : number,
  'quantity' : number,
  'unrealizedPnL' : number,
  'avgBuyPrice' : number,
  'symbol' : string,
}
export type Side = { 'buy' : null } |
  { 'sell' : null };
export type Time = bigint;
export type TradeType = { 'carryForward' : null } |
  { 'intraday' : null };
export interface User {
  'balance' : number,
  'name' : string,
  'email' : string,
  'mobile' : string,
}
export type WithdrawalMethod = { 'upi' : null } |
  { 'bank' : null };
export interface WithdrawalRequestV2 {
  'id' : string,
  'status' : WithdrawalStatus,
  'userEmail' : string,
  'ifscCode' : [] | [string],
  'bankName' : [] | [string],
  'upiId' : [] | [string],
  'withdrawalMethod' : WithdrawalMethod,
  'accountNumber' : [] | [string],
  'amount' : number,
  'requestTime' : Time,
}
export type WithdrawalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface _SERVICE {
  'addToWatchlist' : ActorMethod<[string, string], undefined>,
  'adjustUserBalance' : ActorMethod<
    [string, string, number, boolean],
    undefined
  >,
  'adminClosePosition' : ActorMethod<[string, string, string], undefined>,
  'adminEditPosition' : ActorMethod<
    [string, string, string, number, number],
    undefined
  >,
  'adminResetPassword' : ActorMethod<[string, string, string], undefined>,
  'approveDeposit' : ActorMethod<[string, string], undefined>,
  'approveWithdrawal' : ActorMethod<[string, string], undefined>,
  'authenticate' : ActorMethod<[Principal], boolean>,
  'authenticateAdmin' : ActorMethod<[Principal], boolean>,
  'closePosition' : ActorMethod<[string, string, number], undefined>,
  'createCreditCode' : ActorMethod<[string, string, number], undefined>,
  'createInstrument' : ActorMethod<
    [string, string, Category, number, number],
    undefined
  >,
  'deleteCreditCode' : ActorMethod<[string, string], undefined>,
  'deleteInstrument' : ActorMethod<[string], undefined>,
  'deposit' : ActorMethod<[number], undefined>,
  'getAdminStats' : ActorMethod<[string], AdminStats>,
  'getAllCreditCodes' : ActorMethod<[string], Array<CreditCodeV2>>,
  'getAllDepositRequests' : ActorMethod<[string], Array<DepositRequestV2>>,
  'getAllInstruments' : ActorMethod<[], Array<Instrument>>,
  'getAllOrders' : ActorMethod<[string], Array<OrderV2>>,
  'getAllPositions' : ActorMethod<
    [string],
    Array<[string, Array<PositionSummary>]>
  >,
  'getAllUsers' : ActorMethod<[string], Array<[string, User]>>,
  'getAllWithdrawalRequests' : ActorMethod<
    [string],
    Array<WithdrawalRequestV2>
  >,
  'getAppSettings' : ActorMethod<[], AppSettings>,
  'getAvailableBalance' : ActorMethod<[], number>,
  'getAvailableBalanceByToken' : ActorMethod<[string], number>,
  'getDepositRequests' : ActorMethod<[string], Array<DepositRequestV2>>,
  'getInstrumentsByCategory' : ActorMethod<[Category], Array<Instrument>>,
  'getOpenPositions' : ActorMethod<[string], Array<PositionSummary>>,
  'getOrders' : ActorMethod<[string], Array<OrderV2>>,
  'getPaymentSettings' : ActorMethod<[], [] | [PaymentSettingsV2]>,
  'getPortfolioSummary' : ActorMethod<[string], PortfolioSummary>,
  'getProfileByToken' : ActorMethod<[string], User>,
  'getSessionFull' : ActorMethod<[string], [] | [[User, boolean]]>,
  'getUserByToken' : ActorMethod<[string], [Principal, User]>,
  'getUserProfile' : ActorMethod<[], User>,
  'getUserProfileByToken' : ActorMethod<[string], User>,
  'getWatchlist' : ActorMethod<[string], Array<string>>,
  'getWithdrawalRequests' : ActorMethod<[string], Array<WithdrawalRequestV2>>,
  'isAdminByToken' : ActorMethod<[string], boolean>,
  'isAdminUser' : ActorMethod<[Principal], boolean>,
  'loginFull' : ActorMethod<[string, string], [string, User, boolean]>,
  'loginWithPassword' : ActorMethod<[string, string], string>,
  'logoutByToken' : ActorMethod<[string], undefined>,
  'placeOrder' : ActorMethod<
    [string, string, number, number, OrderType, TradeType, Side],
    string
  >,
  'redeemCreditCode' : ActorMethod<[string, string], undefined>,
  'registerUser' : ActorMethod<[string, string, string], undefined>,
  'registerUserWithPassword' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'rejectDeposit' : ActorMethod<[string, string], undefined>,
  'rejectWithdrawal' : ActorMethod<[string, string], undefined>,
  'removeFromWatchlist' : ActorMethod<[string, string], undefined>,
  'requestDeposit' : ActorMethod<[string, number], string>,
  'requestWithdrawal' : ActorMethod<
    [
      string,
      number,
      WithdrawalMethod,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
    ],
    string
  >,
  'setPaymentSettings' : ActorMethod<
    [string, string, string, string, string, string, string],
    undefined
  >,
  'submitDepositUtr' : ActorMethod<[string, string, string], undefined>,
  'updateAppSettings' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'updateInstrumentPrice' : ActorMethod<[InstrumentUpdate], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];