/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminStats {
  'totalOrders' : bigint,
  'totalInstruments' : bigint,
  'totalUsers' : bigint,
}
export interface AppSettings {
  'privacyText' : string,
  'termsText' : string,
  'stockLossColor' : string,
  'stockGainColor' : string,
}
export type Category = { 'forex' : null } |
  { 'stock' : null } |
  { 'crypto' : null } |
  { 'commodity' : null };
export interface CreditCode {
  'redeemedAt' : [] | [Time],
  'redeemedBy' : [] | [Principal],
  'status' : CreditCodeStatus,
  'code' : string,
  'createdAt' : Time,
  'amount' : number,
}
export type CreditCodeStatus = { 'active' : null } |
  { 'redeemed' : null };
export interface DepositRequest {
  'id' : string,
  'status' : DepositStatus,
  'user' : Principal,
  'utrNumber' : [] | [string],
  'amount' : number,
  'requestTime' : Time,
}
export type DepositStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Instrument {
  'currentPrice' : number,
  'name' : string,
  'previousClose' : number,
  'priceChangePercent' : number,
  'category' : Category,
  'symbol' : string,
}
export interface InstrumentUpdate {
  'currentPrice' : number,
  'previousClose' : number,
  'symbol' : string,
}
export interface Order {
  'id' : string,
  'status' : OrderStatus,
  'tradeType' : TradeType,
  'side' : Side,
  'user' : Principal,
  'orderType' : OrderType,
  'marginUsed' : number,
  'timestamp' : Time,
  'quantity' : number,
  'price' : number,
  'symbol' : string,
}
export type OrderStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'rejected' : null } |
  { 'executed' : null };
export type OrderType = { 'limit' : null } |
  { 'stopLoss' : null } |
  { 'market' : null };
export interface PaymentSettings { 'qrCodeData' : string, 'upiId' : string }
export interface PortfolioSummary {
  'totalInvested' : number,
  'availableBalance' : number,
  'marginAvailable' : number,
  'totalPnL' : number,
  'currentValue' : number,
  'marginUsed' : number,
}
export interface PositionSummary {
  'tradeType' : TradeType,
  'marginUsed' : number,
  'quantity' : number,
  'unrealizedPnL' : number,
  'avgBuyPrice' : number,
  'symbol' : string,
}
export type Side = { 'buy' : null } |
  { 'sell' : null };
export type Time = bigint;
export type TradeType = { 'carryForward' : null } |
  { 'intraday' : null };
export interface User {
  'balance' : number,
  'name' : string,
  'email' : string,
  'mobile' : string,
}
export type WithdrawalMethod = { 'upi' : null } |
  { 'bank' : null };
export interface WithdrawalRequest {
  'id' : string,
  'status' : WithdrawalStatus,
  'ifscCode' : [] | [string],
  'user' : Principal,
  'bankName' : [] | [string],
  'upiId' : [] | [string],
  'withdrawalMethod' : WithdrawalMethod,
  'accountNumber' : [] | [string],
  'amount' : number,
  'requestTime' : Time,
}
export type WithdrawalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface _SERVICE {
  'addToWatchlist' : ActorMethod<[string], undefined>,
  'adjustUserBalance' : ActorMethod<[string, number, boolean], undefined>,
  'adminClosePosition' : ActorMethod<[Principal, string], undefined>,
  'adminEditPosition' : ActorMethod<
    [Principal, string, number, number],
    undefined
  >,
  'adminResetPassword' : ActorMethod<[string, string], undefined>,
  'approveDeposit' : ActorMethod<[string], undefined>,
  'approveWithdrawal' : ActorMethod<[string], undefined>,
  'authenticate' : ActorMethod<[Principal], boolean>,
  'authenticateAdmin' : ActorMethod<[Principal], boolean>,
  'closePosition' : ActorMethod<[string, number], undefined>,
  'createCreditCode' : ActorMethod<[string, number], undefined>,
  'createInstrument' : ActorMethod<
    [string, string, Category, number, number],
    undefined
  >,
  'deleteCreditCode' : ActorMethod<[string], undefined>,
  'deleteInstrument' : ActorMethod<[string], undefined>,
  'deposit' : ActorMethod<[number], undefined>,
  'getAdminStats' : ActorMethod<[], AdminStats>,
  'getAllCreditCodes' : ActorMethod<[], Array<CreditCode>>,
  'getAllDepositRequests' : ActorMethod<[], Array<DepositRequest>>,
  'getAllInstruments' : ActorMethod<[], Array<Instrument>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllPositions' : ActorMethod<
    [],
    Array<[Principal, Array<PositionSummary>]>
  >,
  'getAllUsers' : ActorMethod<[], Array<[Principal, User]>>,
  'getAllWithdrawalRequests' : ActorMethod<[], Array<WithdrawalRequest>>,
  'getAppSettings' : ActorMethod<[], AppSettings>,
  'getAvailableBalance' : ActorMethod<[], number>,
  'getDepositRequests' : ActorMethod<[], Array<DepositRequest>>,
  'getInstrumentsByCategory' : ActorMethod<[Category], Array<Instrument>>,
  'getOpenPositions' : ActorMethod<[], Array<PositionSummary>>,
  'getOrders' : ActorMethod<[], Array<Order>>,
  'getPaymentSettings' : ActorMethod<[], [] | [PaymentSettings]>,
  'getPortfolioSummary' : ActorMethod<[], PortfolioSummary>,
  'getProfileByToken' : ActorMethod<[string], User>,
  'getUserByToken' : ActorMethod<[string], [Principal, User]>,
  'getUserProfile' : ActorMethod<[], User>,
  'getWatchlist' : ActorMethod<[], Array<string>>,
  'getWithdrawalRequests' : ActorMethod<[], Array<WithdrawalRequest>>,
  'isAdminByToken' : ActorMethod<[string], boolean>,
  'isAdminUser' : ActorMethod<[Principal], boolean>,
  'loginWithPassword' : ActorMethod<[string, string], string>,
  'logoutByToken' : ActorMethod<[string], undefined>,
  'placeOrder' : ActorMethod<
    [string, number, number, OrderType, TradeType, Side],
    string
  >,
  'redeemCreditCode' : ActorMethod<[string], undefined>,
  'registerUser' : ActorMethod<[string, string, string], undefined>,
  'registerUserWithPassword' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'rejectDeposit' : ActorMethod<[string], undefined>,
  'rejectWithdrawal' : ActorMethod<[string], undefined>,
  'removeFromWatchlist' : ActorMethod<[string], undefined>,
  'requestDeposit' : ActorMethod<[number], string>,
  'requestWithdrawal' : ActorMethod<
    [
      number,
      WithdrawalMethod,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
    ],
    string
  >,
  'setPaymentSettings' : ActorMethod<[string, string], undefined>,
  'submitDepositUtr' : ActorMethod<[string, string], undefined>,
  'updateAppSettings' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'updateInstrumentPrice' : ActorMethod<[InstrumentUpdate], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];