/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'forex' : IDL.Null,
  'stock' : IDL.Null,
  'crypto' : IDL.Null,
  'commodity' : IDL.Null,
});
export const AdminStats = IDL.Record({
  'totalOrders' : IDL.Nat,
  'totalInstruments' : IDL.Nat,
  'totalUsers' : IDL.Nat,
});
export const Time = IDL.Int;
export const CreditCodeStatus = IDL.Variant({
  'active' : IDL.Null,
  'redeemed' : IDL.Null,
});
export const CreditCodeV2 = IDL.Record({
  'redeemedAt' : IDL.Opt(Time),
  'redeemedBy' : IDL.Opt(IDL.Text),
  'status' : CreditCodeStatus,
  'code' : IDL.Text,
  'createdAt' : Time,
  'amount' : IDL.Float64,
});
export const DepositStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const DepositRequestV2 = IDL.Record({
  'id' : IDL.Text,
  'status' : DepositStatus,
  'userEmail' : IDL.Text,
  'utrNumber' : IDL.Opt(IDL.Text),
  'amount' : IDL.Float64,
  'requestTime' : Time,
});
export const Instrument = IDL.Record({
  'currentPrice' : IDL.Float64,
  'name' : IDL.Text,
  'previousClose' : IDL.Float64,
  'priceChangePercent' : IDL.Float64,
  'category' : Category,
  'symbol' : IDL.Text,
});
export const OrderStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
  'executed' : IDL.Null,
});
export const TradeType = IDL.Variant({
  'carryForward' : IDL.Null,
  'intraday' : IDL.Null,
});
export const Side = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
export const OrderType = IDL.Variant({
  'limit' : IDL.Null,
  'stopLoss' : IDL.Null,
  'market' : IDL.Null,
});
export const OrderV2 = IDL.Record({
  'id' : IDL.Text,
  'status' : OrderStatus,
  'tradeType' : TradeType,
  'side' : Side,
  'userEmail' : IDL.Text,
  'orderType' : OrderType,
  'marginUsed' : IDL.Float64,
  'timestamp' : Time,
  'quantity' : IDL.Float64,
  'price' : IDL.Float64,
  'symbol' : IDL.Text,
});
export const PositionSummary = IDL.Record({
  'tradeType' : TradeType,
  'marginUsed' : IDL.Float64,
  'quantity' : IDL.Float64,
  'unrealizedPnL' : IDL.Float64,
  'avgBuyPrice' : IDL.Float64,
  'symbol' : IDL.Text,
});
export const User = IDL.Record({
  'balance' : IDL.Float64,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'mobile' : IDL.Text,
});
export const WithdrawalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const WithdrawalMethod = IDL.Variant({ 'upi' : IDL.Null, 'bank' : IDL.Null });
export const WithdrawalRequestV2 = IDL.Record({
  'id' : IDL.Text,
  'status' : WithdrawalStatus,
  'ifscCode' : IDL.Opt(IDL.Text),
  'userEmail' : IDL.Text,
  'bankName' : IDL.Opt(IDL.Text),
  'upiId' : IDL.Opt(IDL.Text),
  'withdrawalMethod' : WithdrawalMethod,
  'accountNumber' : IDL.Opt(IDL.Text),
  'amount' : IDL.Float64,
  'requestTime' : Time,
});
export const AppSettings = IDL.Record({
  'privacyText' : IDL.Text,
  'termsText' : IDL.Text,
  'stockLossColor' : IDL.Text,
  'stockGainColor' : IDL.Text,
});
export const PaymentSettingsV2 = IDL.Record({
  'qrCodeData' : IDL.Text,
  'upiId' : IDL.Text,
  'bankAccountHolder' : IDL.Text,
  'bankName' : IDL.Text,
  'bankAccountNumber' : IDL.Text,
  'bankIfsc' : IDL.Text,
});
export const PortfolioSummary = IDL.Record({
  'totalInvested' : IDL.Float64,
  'availableBalance' : IDL.Float64,
  'marginAvailable' : IDL.Float64,
  'totalPnL' : IDL.Float64,
  'currentValue' : IDL.Float64,
  'marginUsed' : IDL.Float64,
});
export const InstrumentUpdate = IDL.Record({
  'currentPrice' : IDL.Float64,
  'previousClose' : IDL.Float64,
  'symbol' : IDL.Text,
});

export const idlService = IDL.Service({
  'addToWatchlist' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'adjustUserBalance' : IDL.Func([IDL.Text, IDL.Text, IDL.Float64, IDL.Bool], [], []),
  'adminClosePosition' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'adminEditPosition' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Float64], [], []),
  'adminResetPassword' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'approveDeposit' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'approveWithdrawal' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'authenticate' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  'authenticateAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  'closePosition' : IDL.Func([IDL.Text, IDL.Text, IDL.Float64], [], []),
  'createCreditCode' : IDL.Func([IDL.Text, IDL.Text, IDL.Float64], [], []),
  'createInstrument' : IDL.Func([IDL.Text, IDL.Text, Category, IDL.Float64, IDL.Float64], [], []),
  'deleteCreditCode' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteInstrument' : IDL.Func([IDL.Text], [], []),
  'deposit' : IDL.Func([IDL.Float64], [], []),
  'getAdminStats' : IDL.Func([IDL.Text], [AdminStats], []),
  'getAllCreditCodes' : IDL.Func([IDL.Text], [IDL.Vec(CreditCodeV2)], []),
  'getAllDepositRequests' : IDL.Func([IDL.Text], [IDL.Vec(DepositRequestV2)], []),
  'getAllInstruments' : IDL.Func([], [IDL.Vec(Instrument)], ['query']),
  'getAllOrders' : IDL.Func([IDL.Text], [IDL.Vec(OrderV2)], []),
  'getAllPositions' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(PositionSummary)))], []),
  'getAllUsers' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Tuple(IDL.Text, User))], []),
  'getAllWithdrawalRequests' : IDL.Func([IDL.Text], [IDL.Vec(WithdrawalRequestV2)], []),
  'getAppSettings' : IDL.Func([], [AppSettings], ['query']),
  'getAvailableBalance' : IDL.Func([], [IDL.Float64], ['query']),
  'getAvailableBalanceByToken' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
  'getDepositRequests' : IDL.Func([IDL.Text], [IDL.Vec(DepositRequestV2)], ['query']),
  'getInstrumentsByCategory' : IDL.Func([Category], [IDL.Vec(Instrument)], ['query']),
  'getOpenPositions' : IDL.Func([IDL.Text], [IDL.Vec(PositionSummary)], ['query']),
  'getOrders' : IDL.Func([IDL.Text], [IDL.Vec(OrderV2)], ['query']),
  'getPaymentSettings' : IDL.Func([], [IDL.Opt(PaymentSettingsV2)], ['query']),
  'getPortfolioSummary' : IDL.Func([IDL.Text], [PortfolioSummary], ['query']),
  'getProfileByToken' : IDL.Func([IDL.Text], [User], ['query']),
  'getSessionFull' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Tuple(User, IDL.Bool))], ['query']),
  'getUserByToken' : IDL.Func([IDL.Text], [IDL.Principal, User], ['query']),
  'getUserProfile' : IDL.Func([], [User], ['query']),
  'getUserProfileByToken' : IDL.Func([IDL.Text], [User], ['query']),
  'getWatchlist' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'getWithdrawalRequests' : IDL.Func([IDL.Text], [IDL.Vec(WithdrawalRequestV2)], ['query']),
  'isAdminByToken' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'isAdminUser' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'loginFull' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text, User, IDL.Bool], []),
  'loginWithPassword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'logoutByToken' : IDL.Func([IDL.Text], [], []),
  'placeOrder' : IDL.Func([IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, OrderType, TradeType, Side], [IDL.Text], []),
  'redeemCreditCode' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'registerUserWithPassword' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'rejectDeposit' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'rejectWithdrawal' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'removeFromWatchlist' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'requestDeposit' : IDL.Func([IDL.Text, IDL.Float64], [IDL.Text], []),
  'requestWithdrawal' : IDL.Func([IDL.Text, IDL.Float64, WithdrawalMethod, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)], [IDL.Text], []),
  'setPaymentSettings' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'submitDepositUtr' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateAppSettings' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateInstrumentPrice' : IDL.Func([InstrumentUpdate], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'forex' : IDL.Null,
    'stock' : IDL.Null,
    'crypto' : IDL.Null,
    'commodity' : IDL.Null,
  });
  const AdminStats = IDL.Record({
    'totalOrders' : IDL.Nat,
    'totalInstruments' : IDL.Nat,
    'totalUsers' : IDL.Nat,
  });
  const Time = IDL.Int;
  const CreditCodeStatus = IDL.Variant({
    'active' : IDL.Null,
    'redeemed' : IDL.Null,
  });
  const CreditCodeV2 = IDL.Record({
    'redeemedAt' : IDL.Opt(Time),
    'redeemedBy' : IDL.Opt(IDL.Text),
    'status' : CreditCodeStatus,
    'code' : IDL.Text,
    'createdAt' : Time,
    'amount' : IDL.Float64,
  });
  const DepositStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const DepositRequestV2 = IDL.Record({
    'id' : IDL.Text,
    'status' : DepositStatus,
    'userEmail' : IDL.Text,
    'utrNumber' : IDL.Opt(IDL.Text),
    'amount' : IDL.Float64,
    'requestTime' : Time,
  });
  const Instrument = IDL.Record({
    'currentPrice' : IDL.Float64,
    'name' : IDL.Text,
    'previousClose' : IDL.Float64,
    'priceChangePercent' : IDL.Float64,
    'category' : Category,
    'symbol' : IDL.Text,
  });
  const OrderStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
    'executed' : IDL.Null,
  });
  const TradeType = IDL.Variant({
    'carryForward' : IDL.Null,
    'intraday' : IDL.Null,
  });
  const Side = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
  const OrderType = IDL.Variant({
    'limit' : IDL.Null,
    'stopLoss' : IDL.Null,
    'market' : IDL.Null,
  });
  const OrderV2 = IDL.Record({
    'id' : IDL.Text,
    'status' : OrderStatus,
    'tradeType' : TradeType,
    'side' : Side,
    'userEmail' : IDL.Text,
    'orderType' : OrderType,
    'marginUsed' : IDL.Float64,
    'timestamp' : Time,
    'quantity' : IDL.Float64,
    'price' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  const PositionSummary = IDL.Record({
    'tradeType' : TradeType,
    'marginUsed' : IDL.Float64,
    'quantity' : IDL.Float64,
    'unrealizedPnL' : IDL.Float64,
    'avgBuyPrice' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  const User = IDL.Record({
    'balance' : IDL.Float64,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'mobile' : IDL.Text,
  });
  const WithdrawalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const WithdrawalMethod = IDL.Variant({ 'upi' : IDL.Null, 'bank' : IDL.Null });
  const WithdrawalRequestV2 = IDL.Record({
    'id' : IDL.Text,
    'status' : WithdrawalStatus,
    'ifscCode' : IDL.Opt(IDL.Text),
    'userEmail' : IDL.Text,
    'bankName' : IDL.Opt(IDL.Text),
    'upiId' : IDL.Opt(IDL.Text),
    'withdrawalMethod' : WithdrawalMethod,
    'accountNumber' : IDL.Opt(IDL.Text),
    'amount' : IDL.Float64,
    'requestTime' : Time,
  });
  const AppSettings = IDL.Record({
    'privacyText' : IDL.Text,
    'termsText' : IDL.Text,
    'stockLossColor' : IDL.Text,
    'stockGainColor' : IDL.Text,
  });
  const PaymentSettingsV2 = IDL.Record({
    'qrCodeData' : IDL.Text,
    'upiId' : IDL.Text,
    'bankAccountHolder' : IDL.Text,
    'bankName' : IDL.Text,
    'bankAccountNumber' : IDL.Text,
    'bankIfsc' : IDL.Text,
  });
  const PortfolioSummary = IDL.Record({
    'totalInvested' : IDL.Float64,
    'availableBalance' : IDL.Float64,
    'marginAvailable' : IDL.Float64,
    'totalPnL' : IDL.Float64,
    'currentValue' : IDL.Float64,
    'marginUsed' : IDL.Float64,
  });
  const InstrumentUpdate = IDL.Record({
    'currentPrice' : IDL.Float64,
    'previousClose' : IDL.Float64,
    'symbol' : IDL.Text,
  });

  return IDL.Service({
    'addToWatchlist' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'adjustUserBalance' : IDL.Func([IDL.Text, IDL.Text, IDL.Float64, IDL.Bool], [], []),
    'adminClosePosition' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'adminEditPosition' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Float64], [], []),
    'adminResetPassword' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'approveDeposit' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'approveWithdrawal' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'authenticate' : IDL.Func([IDL.Principal], [IDL.Bool], []),
    'authenticateAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], []),
    'closePosition' : IDL.Func([IDL.Text, IDL.Text, IDL.Float64], [], []),
    'createCreditCode' : IDL.Func([IDL.Text, IDL.Text, IDL.Float64], [], []),
    'createInstrument' : IDL.Func([IDL.Text, IDL.Text, Category, IDL.Float64, IDL.Float64], [], []),
    'deleteCreditCode' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteInstrument' : IDL.Func([IDL.Text], [], []),
    'deposit' : IDL.Func([IDL.Float64], [], []),
    'getAdminStats' : IDL.Func([IDL.Text], [AdminStats], []),
    'getAllCreditCodes' : IDL.Func([IDL.Text], [IDL.Vec(CreditCodeV2)], []),
    'getAllDepositRequests' : IDL.Func([IDL.Text], [IDL.Vec(DepositRequestV2)], []),
    'getAllInstruments' : IDL.Func([], [IDL.Vec(Instrument)], ['query']),
    'getAllOrders' : IDL.Func([IDL.Text], [IDL.Vec(OrderV2)], []),
    'getAllPositions' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(PositionSummary)))], []),
    'getAllUsers' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Tuple(IDL.Text, User))], []),
    'getAllWithdrawalRequests' : IDL.Func([IDL.Text], [IDL.Vec(WithdrawalRequestV2)], []),
    'getAppSettings' : IDL.Func([], [AppSettings], ['query']),
    'getAvailableBalance' : IDL.Func([], [IDL.Float64], ['query']),
    'getAvailableBalanceByToken' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
    'getDepositRequests' : IDL.Func([IDL.Text], [IDL.Vec(DepositRequestV2)], ['query']),
    'getInstrumentsByCategory' : IDL.Func([Category], [IDL.Vec(Instrument)], ['query']),
    'getOpenPositions' : IDL.Func([IDL.Text], [IDL.Vec(PositionSummary)], ['query']),
    'getOrders' : IDL.Func([IDL.Text], [IDL.Vec(OrderV2)], ['query']),
    'getPaymentSettings' : IDL.Func([], [IDL.Opt(PaymentSettingsV2)], ['query']),
    'getPortfolioSummary' : IDL.Func([IDL.Text], [PortfolioSummary], ['query']),
    'getProfileByToken' : IDL.Func([IDL.Text], [User], ['query']),
    'getSessionFull' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Tuple(User, IDL.Bool))], ['query']),
    'getUserByToken' : IDL.Func([IDL.Text], [IDL.Principal, User], ['query']),
    'getUserProfile' : IDL.Func([], [User], ['query']),
    'getUserProfileByToken' : IDL.Func([IDL.Text], [User], ['query']),
    'getWatchlist' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
    'getWithdrawalRequests' : IDL.Func([IDL.Text], [IDL.Vec(WithdrawalRequestV2)], ['query']),
    'isAdminByToken' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'isAdminUser' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'loginFull' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text, User, IDL.Bool], []),
    'loginWithPassword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'logoutByToken' : IDL.Func([IDL.Text], [], []),
    'placeOrder' : IDL.Func([IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, OrderType, TradeType, Side], [IDL.Text], []),
    'redeemCreditCode' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'registerUserWithPassword' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'rejectDeposit' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'rejectWithdrawal' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'removeFromWatchlist' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'requestDeposit' : IDL.Func([IDL.Text, IDL.Float64], [IDL.Text], []),
    'requestWithdrawal' : IDL.Func([IDL.Text, IDL.Float64, WithdrawalMethod, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)], [IDL.Text], []),
    'setPaymentSettings' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'submitDepositUtr' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateAppSettings' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateInstrumentPrice' : IDL.Func([InstrumentUpdate], [], []),
  });
};

export const init = ({ IDL }) => { return []; };
