/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface InstrumentUpdate {
    currentPrice: number;
    previousClose: number;
    symbol: string;
}
export type Time = bigint;
export interface Instrument {
    currentPrice: number;
    name: string;
    previousClose: number;
    priceChangePercent: number;
    category: Category;
    symbol: string;
}
export interface User {
    balance: number;
    name: string;
    email: string;
    mobile: string;
}
export interface PositionSummary {
    tradeType: TradeType;
    marginUsed: number;
    quantity: number;
    unrealizedPnL: number;
    avgBuyPrice: number;
    symbol: string;
}
export interface PortfolioSummary {
    totalInvested: number;
    availableBalance: number;
    marginAvailable: number;
    totalPnL: number;
    currentValue: number;
    marginUsed: number;
}
export interface Order {
    id: string;
    status: OrderStatus;
    tradeType: TradeType;
    side: Side;
    user: Principal;
    orderType: OrderType;
    marginUsed: number;
    timestamp: Time;
    quantity: number;
    price: number;
    symbol: string;
}
export interface PaymentSettings {
    qrCodeData: string;
    upiId: string;
}
export interface AdminStats {
    totalOrders: bigint;
    totalInstruments: bigint;
    totalUsers: bigint;
}
export interface WithdrawalRequest {
    id: string;
    status: WithdrawalStatus;
    ifscCode?: string;
    user: Principal;
    bankName?: string;
    upiId?: string;
    withdrawalMethod: WithdrawalMethod;
    accountNumber?: string;
    amount: number;
    requestTime: Time;
}
export enum Category {
    forex = "forex",
    stock = "stock",
    crypto = "crypto",
    commodity = "commodity"
}
export enum OrderStatus {
    cancelled = "cancelled",
    pending = "pending",
    rejected = "rejected",
    executed = "executed"
}
export enum OrderType {
    limit = "limit",
    stopLoss = "stopLoss",
    market = "market"
}
export enum Side {
    buy = "buy",
    sell = "sell"
}
export enum TradeType {
    carryForward = "carryForward",
    intraday = "intraday"
}
export enum WithdrawalMethod {
    upi = "upi",
    bank = "bank"
}
export enum WithdrawalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export interface backendInterface {
    addToWatchlist(symbol: string): Promise<void>;
    approveWithdrawal(requestId: string): Promise<void>;
    authenticate(userPrincipal: Principal): Promise<boolean>;
    authenticateAdmin(userPrincipal: Principal): Promise<boolean>;
    closePosition(symbol: string, quantity: number): Promise<void>;
    createInstrument(symbol: string, name: string, category: Category, currentPrice: number, previousClose: number): Promise<void>;
    deleteInstrument(symbol: string): Promise<void>;
    deposit(amount: number): Promise<void>;
    getAdminStats(): Promise<AdminStats>;
    getAllInstruments(): Promise<Array<Instrument>>;
    getAllOrders(): Promise<Array<Order>>;
    getAllUsers(): Promise<Array<[Principal, User]>>;
    getAllWithdrawalRequests(): Promise<Array<WithdrawalRequest>>;
    getAvailableBalance(): Promise<number>;
    getInstrumentsByCategory(category: Category): Promise<Array<Instrument>>;
    getOpenPositions(): Promise<Array<PositionSummary>>;
    getOrders(): Promise<Array<Order>>;
    getPaymentSettings(): Promise<PaymentSettings | null>;
    getPortfolioSummary(): Promise<PortfolioSummary>;
    getUserProfile(): Promise<User>;
    getWatchlist(): Promise<Array<string>>;
    getWithdrawalRequests(): Promise<Array<WithdrawalRequest>>;
    isAdminUser(p: Principal): Promise<boolean>;
    placeOrder(symbol: string, quantity: number, price: number, orderType: OrderType, tradeType: TradeType, side: Side): Promise<string>;
    registerUser(name: string, email: string, mobile: string): Promise<void>;
    rejectWithdrawal(requestId: string): Promise<void>;
    removeFromWatchlist(symbol: string): Promise<void>;
    requestWithdrawal(amount: number, withdrawalMethod: WithdrawalMethod, upiId: string | null, bankName: string | null, accountNumber: string | null, ifscCode: string | null): Promise<string>;
    setPaymentSettings(upiId: string, qrCodeData: string): Promise<void>;
    updateInstrumentPrice(update: InstrumentUpdate): Promise<void>;
}
import type { Category as _Category, Instrument as _Instrument, Order as _Order, OrderStatus as _OrderStatus, OrderType as _OrderType, PaymentSettings as _PaymentSettings, PositionSummary as _PositionSummary, Side as _Side, Time as _Time, TradeType as _TradeType, WithdrawalMethod as _WithdrawalMethod, WithdrawalRequest as _WithdrawalRequest, WithdrawalStatus as _WithdrawalStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addToWatchlist(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addToWatchlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToWatchlist(arg0);
            return result;
        }
    }
    async approveWithdrawal(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveWithdrawal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveWithdrawal(arg0);
            return result;
        }
    }
    async authenticate(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.authenticate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.authenticate(arg0);
            return result;
        }
    }
    async authenticateAdmin(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.authenticateAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.authenticateAdmin(arg0);
            return result;
        }
    }
    async closePosition(arg0: string, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.closePosition(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.closePosition(arg0, arg1);
            return result;
        }
    }
    async createInstrument(arg0: string, arg1: string, arg2: Category, arg3: number, arg4: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createInstrument(arg0, arg1, to_candid_Category_n1(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInstrument(arg0, arg1, to_candid_Category_n1(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
            return result;
        }
    }
    async deleteInstrument(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInstrument(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInstrument(arg0);
            return result;
        }
    }
    async deposit(arg0: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deposit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deposit(arg0);
            return result;
        }
    }
    async getAdminStats(): Promise<AdminStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminStats();
            return result;
        }
    }
    async getAllInstruments(): Promise<Array<Instrument>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInstruments();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInstruments();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOrders();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOrders();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsers(): Promise<Array<[Principal, User]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return result;
        }
    }
    async getAllWithdrawalRequests(): Promise<Array<WithdrawalRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWithdrawalRequests();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWithdrawalRequests();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailableBalance(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableBalance();
            return result;
        }
    }
    async getInstrumentsByCategory(arg0: Category): Promise<Array<Instrument>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInstrumentsByCategory(to_candid_Category_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInstrumentsByCategory(to_candid_Category_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOpenPositions(): Promise<Array<PositionSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOpenPositions();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOpenPositions();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrders();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrders();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPaymentSettings(): Promise<PaymentSettings | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentSettings();
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentSettings();
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPortfolioSummary(): Promise<PortfolioSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getPortfolioSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPortfolioSummary();
            return result;
        }
    }
    async getUserProfile(): Promise<User> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile();
            return result;
        }
    }
    async getWatchlist(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWatchlist();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWatchlist();
            return result;
        }
    }
    async getWithdrawalRequests(): Promise<Array<WithdrawalRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWithdrawalRequests();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWithdrawalRequests();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async isAdminUser(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdminUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdminUser(arg0);
            return result;
        }
    }
    async placeOrder(arg0: string, arg1: number, arg2: number, arg3: OrderType, arg4: TradeType, arg5: Side): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrder(arg0, arg1, arg2, to_candid_OrderType_n31(this._uploadFile, this._downloadFile, arg3), to_candid_TradeType_n33(this._uploadFile, this._downloadFile, arg4), to_candid_Side_n35(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrder(arg0, arg1, arg2, to_candid_OrderType_n31(this._uploadFile, this._downloadFile, arg3), to_candid_TradeType_n33(this._uploadFile, this._downloadFile, arg4), to_candid_Side_n35(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async registerUser(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, arg1, arg2);
            return result;
        }
    }
    async rejectWithdrawal(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectWithdrawal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectWithdrawal(arg0);
            return result;
        }
    }
    async removeFromWatchlist(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromWatchlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromWatchlist(arg0);
            return result;
        }
    }
    async requestWithdrawal(arg0: number, arg1: WithdrawalMethod, arg2: string | null, arg3: string | null, arg4: string | null, arg5: string | null): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.requestWithdrawal(arg0, to_candid_WithdrawalMethod_n37(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n39(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n39(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n39(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n39(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestWithdrawal(arg0, to_candid_WithdrawalMethod_n37(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n39(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n39(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n39(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n39(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async setPaymentSettings(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setPaymentSettings(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPaymentSettings(arg0, arg1);
            return result;
        }
    }
    async updateInstrumentPrice(arg0: InstrumentUpdate): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInstrumentPrice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInstrumentPrice(arg0);
            return result;
        }
    }
}
function from_candid_Category_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Instrument_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Instrument): Instrument {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_OrderType_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderType): OrderType {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_PositionSummary_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PositionSummary): PositionSummary {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_Side_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Side): Side {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_TradeType_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TradeType): TradeType {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_WithdrawalMethod_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WithdrawalMethod): WithdrawalMethod {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_WithdrawalRequest_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WithdrawalRequest): WithdrawalRequest {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_WithdrawalStatus_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WithdrawalStatus): WithdrawalStatus {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PaymentSettings]): PaymentSettings | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _OrderStatus;
    tradeType: _TradeType;
    side: _Side;
    user: Principal;
    orderType: _OrderType;
    marginUsed: number;
    timestamp: _Time;
    quantity: number;
    price: number;
    symbol: string;
}): {
    id: string;
    status: OrderStatus;
    tradeType: TradeType;
    side: Side;
    user: Principal;
    orderType: OrderType;
    marginUsed: number;
    timestamp: Time;
    quantity: number;
    price: number;
    symbol: string;
} {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n11(_uploadFile, _downloadFile, value.status),
        tradeType: from_candid_TradeType_n13(_uploadFile, _downloadFile, value.tradeType),
        side: from_candid_Side_n15(_uploadFile, _downloadFile, value.side),
        user: value.user,
        orderType: from_candid_OrderType_n17(_uploadFile, _downloadFile, value.orderType),
        marginUsed: value.marginUsed,
        timestamp: value.timestamp,
        quantity: value.quantity,
        price: value.price,
        symbol: value.symbol
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _WithdrawalStatus;
    ifscCode: [] | [string];
    user: Principal;
    bankName: [] | [string];
    upiId: [] | [string];
    withdrawalMethod: _WithdrawalMethod;
    accountNumber: [] | [string];
    amount: number;
    requestTime: _Time;
}): {
    id: string;
    status: WithdrawalStatus;
    ifscCode?: string;
    user: Principal;
    bankName?: string;
    upiId?: string;
    withdrawalMethod: WithdrawalMethod;
    accountNumber?: string;
    amount: number;
    requestTime: Time;
} {
    return {
        id: value.id,
        status: from_candid_WithdrawalStatus_n22(_uploadFile, _downloadFile, value.status),
        ifscCode: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.ifscCode)),
        user: value.user,
        bankName: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.bankName)),
        upiId: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.upiId)),
        withdrawalMethod: from_candid_WithdrawalMethod_n25(_uploadFile, _downloadFile, value.withdrawalMethod),
        accountNumber: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.accountNumber)),
        amount: value.amount,
        requestTime: value.requestTime
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tradeType: _TradeType;
    marginUsed: number;
    quantity: number;
    unrealizedPnL: number;
    avgBuyPrice: number;
    symbol: string;
}): {
    tradeType: TradeType;
    marginUsed: number;
    quantity: number;
    unrealizedPnL: number;
    avgBuyPrice: number;
    symbol: string;
} {
    return {
        tradeType: from_candid_TradeType_n13(_uploadFile, _downloadFile, value.tradeType),
        marginUsed: value.marginUsed,
        quantity: value.quantity,
        unrealizedPnL: value.unrealizedPnL,
        avgBuyPrice: value.avgBuyPrice,
        symbol: value.symbol
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    currentPrice: number;
    name: string;
    previousClose: number;
    priceChangePercent: number;
    category: _Category;
    symbol: string;
}): {
    currentPrice: number;
    name: string;
    previousClose: number;
    priceChangePercent: number;
    category: Category;
    symbol: string;
} {
    return {
        currentPrice: value.currentPrice,
        name: value.name,
        previousClose: value.previousClose,
        priceChangePercent: value.priceChangePercent,
        category: from_candid_Category_n6(_uploadFile, _downloadFile, value.category),
        symbol: value.symbol
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    rejected: null;
} | {
    executed: null;
}): OrderStatus {
    return "cancelled" in value ? OrderStatus.cancelled : "pending" in value ? OrderStatus.pending : "rejected" in value ? OrderStatus.rejected : "executed" in value ? OrderStatus.executed : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    carryForward: null;
} | {
    intraday: null;
}): TradeType {
    return "carryForward" in value ? TradeType.carryForward : "intraday" in value ? TradeType.intraday : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    buy: null;
} | {
    sell: null;
}): Side {
    return "buy" in value ? Side.buy : "sell" in value ? Side.sell : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    limit: null;
} | {
    stopLoss: null;
} | {
    market: null;
}): OrderType {
    return "limit" in value ? OrderType.limit : "stopLoss" in value ? OrderType.stopLoss : "market" in value ? OrderType.market : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): WithdrawalStatus {
    return "pending" in value ? WithdrawalStatus.pending : "approved" in value ? WithdrawalStatus.approved : "rejected" in value ? WithdrawalStatus.rejected : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    upi: null;
} | {
    bank: null;
}): WithdrawalMethod {
    return "upi" in value ? WithdrawalMethod.upi : "bank" in value ? WithdrawalMethod.bank : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    forex: null;
} | {
    stock: null;
} | {
    crypto: null;
} | {
    commodity: null;
}): Category {
    return "forex" in value ? Category.forex : "stock" in value ? Category.stock : "crypto" in value ? Category.crypto : "commodity" in value ? Category.commodity : value;
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WithdrawalRequest>): Array<WithdrawalRequest> {
    return value.map((x)=>from_candid_WithdrawalRequest_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PositionSummary>): Array<PositionSummary> {
    return value.map((x)=>from_candid_PositionSummary_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Instrument>): Array<Instrument> {
    return value.map((x)=>from_candid_Instrument_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n9(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_OrderType_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderType): _OrderType {
    return to_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function to_candid_Side_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Side): _Side {
    return to_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function to_candid_TradeType_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradeType): _TradeType {
    return to_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function to_candid_WithdrawalMethod_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WithdrawalMethod): _WithdrawalMethod {
    return to_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    forex: null;
} | {
    stock: null;
} | {
    crypto: null;
} | {
    commodity: null;
} {
    return value == Category.forex ? {
        forex: null
    } : value == Category.stock ? {
        stock: null
    } : value == Category.crypto ? {
        crypto: null
    } : value == Category.commodity ? {
        commodity: null
    } : value;
}
function to_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderType): {
    limit: null;
} | {
    stopLoss: null;
} | {
    market: null;
} {
    return value == OrderType.limit ? {
        limit: null
    } : value == OrderType.stopLoss ? {
        stopLoss: null
    } : value == OrderType.market ? {
        market: null
    } : value;
}
function to_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradeType): {
    carryForward: null;
} | {
    intraday: null;
} {
    return value == TradeType.carryForward ? {
        carryForward: null
    } : value == TradeType.intraday ? {
        intraday: null
    } : value;
}
function to_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Side): {
    buy: null;
} | {
    sell: null;
} {
    return value == Side.buy ? {
        buy: null
    } : value == Side.sell ? {
        sell: null
    } : value;
}
function to_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WithdrawalMethod): {
    upi: null;
} | {
    bank: null;
} {
    return value == WithdrawalMethod.upi ? {
        upi: null
    } : value == WithdrawalMethod.bank ? {
        bank: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
