/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface InstrumentUpdate {
    currentPrice: number;
    previousClose: number;
    symbol: string;
}
export type Time = bigint;
export interface Instrument {
    currentPrice: number;
    name: string;
    previousClose: number;
    priceChangePercent: number;
    category: Category;
    symbol: string;
}
export interface User {
    balance: number;
    name: string;
    email: string;
    mobile: string;
}
export interface PositionSummary {
    tradeType: TradeType;
    marginUsed: number;
    quantity: number;
    unrealizedPnL: number;
    avgBuyPrice: number;
    symbol: string;
}
export interface PortfolioSummary {
    totalInvested: number;
    availableBalance: number;
    marginAvailable: number;
    totalPnL: number;
    currentValue: number;
    marginUsed: number;
}
export interface AppSettings {
    privacyText: string;
    termsText: string;
    stockLossColor: string;
    stockGainColor: string;
}
export interface OrderV2 {
    id: string;
    status: OrderStatus;
    userEmail: string;
    tradeType: TradeType;
    side: Side;
    orderType: OrderType;
    marginUsed: number;
    timestamp: Time;
    quantity: number;
    price: number;
    symbol: string;
}
export interface PaymentSettingsV2 {
    bankAccountNumber: string;
    qrCodeData: string;
    bankAccountHolder: string;
    bankIfsc: string;
    bankName: string;
    upiId: string;
}
export interface DepositRequestV2 {
    id: string;
    status: DepositStatus;
    userEmail: string;
    utrNumber?: string;
    amount: number;
    requestTime: Time;
}
export interface AdminStats {
    totalOrders: bigint;
    totalInstruments: bigint;
    totalUsers: bigint;
}
export interface CreditCodeV2 {
    redeemedAt?: Time;
    redeemedBy?: string;
    status: CreditCodeStatus;
    code: string;
    createdAt: Time;
    amount: number;
}
export interface WithdrawalRequestV2 {
    id: string;
    status: WithdrawalStatus;
    userEmail: string;
    ifscCode?: string;
    bankName?: string;
    upiId?: string;
    withdrawalMethod: WithdrawalMethod;
    accountNumber?: string;
    amount: number;
    requestTime: Time;
}
export enum Category {
    forex = "forex",
    stock = "stock",
    crypto = "crypto",
    commodity = "commodity"
}
export enum CreditCodeStatus {
    active = "active",
    redeemed = "redeemed"
}
export enum DepositStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum OrderStatus {
    cancelled = "cancelled",
    pending = "pending",
    rejected = "rejected",
    executed = "executed"
}
export enum OrderType {
    limit = "limit",
    stopLoss = "stopLoss",
    market = "market"
}
export enum Side {
    buy = "buy",
    sell = "sell"
}
export enum TradeType {
    carryForward = "carryForward",
    intraday = "intraday"
}
export enum WithdrawalMethod {
    upi = "upi",
    bank = "bank"
}
export interface backendInterface {
    addToWatchlist(token: string, symbol: string): Promise<void>;
    adjustUserBalance(token: string, targetEmail: string, amount: number, isDeduct: boolean): Promise<void>;
    adminClosePosition(token: string, targetEmail: string, symbol: string): Promise<void>;
    adminEditPosition(token: string, targetEmail: string, symbol: string, newQuantity: number, newAvgPrice: number): Promise<void>;
    adminResetPassword(token: string, targetEmail: string, newPassword: string): Promise<void>;
    approveDeposit(token: string, requestId: string): Promise<void>;
    approveWithdrawal(token: string, requestId: string): Promise<void>;
    authenticate(userPrincipal: Principal): Promise<boolean>;
    authenticateAdmin(userPrincipal: Principal): Promise<boolean>;
    closePosition(token: string, symbol: string, quantity: number): Promise<void>;
    createCreditCode(token: string, code: string, amount: number): Promise<void>;
    createInstrument(symbol: string, name: string, category: Category, currentPrice: number, previousClose: number): Promise<void>;
    deleteCreditCode(token: string, code: string): Promise<void>;
    deleteInstrument(symbol: string): Promise<void>;
    deposit(amount: number): Promise<void>;
    getAdminStats(token: string): Promise<AdminStats>;
    getAllCreditCodes(token: string): Promise<Array<CreditCodeV2>>;
    getAllDepositRequests(token: string): Promise<Array<DepositRequestV2>>;
    getAllInstruments(): Promise<Array<Instrument>>;
    getAllOrders(token: string): Promise<Array<OrderV2>>;
    getAllPositions(token: string): Promise<Array<[string, Array<PositionSummary>]>>;
    getAllUsers(token: string): Promise<Array<[string, User]>>;
    getAllWithdrawalRequests(token: string): Promise<Array<WithdrawalRequestV2>>;
    getAppSettings(): Promise<AppSettings>;
    getAvailableBalance(): Promise<number>;
    getAvailableBalanceByToken(token: string): Promise<number>;
    getDepositRequests(token: string): Promise<Array<DepositRequestV2>>;
    getInstrumentsByCategory(category: Category): Promise<Array<Instrument>>;
    getOpenPositions(token: string): Promise<Array<PositionSummary>>;
    getOrders(token: string): Promise<Array<OrderV2>>;
    getPaymentSettings(): Promise<PaymentSettingsV2 | null>;
    getPortfolioSummary(token: string): Promise<PortfolioSummary>;
    getProfileByToken(token: string): Promise<User>;
    getSessionFull(token: string): Promise<[User, boolean] | null>;
    getUserByToken(token: string): Promise<[Principal, User]>;
    getUserProfile(): Promise<User>;
    getUserProfileByToken(token: string): Promise<User>;
    getWatchlist(token: string): Promise<Array<string>>;
    getWithdrawalRequests(token: string): Promise<Array<WithdrawalRequestV2>>;
    isAdminByToken(token: string): Promise<boolean>;
    isAdminUser(p: Principal): Promise<boolean>;
    loginFull(email: string, password: string): Promise<[string, User, boolean]>;
    loginWithPassword(email: string, password: string): Promise<string>;
    logoutByToken(token: string): Promise<void>;
    placeOrder(token: string, symbol: string, quantity: number, price: number, orderType: OrderType, tradeType: TradeType, side: Side): Promise<string>;
    redeemCreditCode(token: string, code: string): Promise<void>;
    registerUser(name: string, email: string, mobile: string): Promise<void>;
    registerUserWithPassword(name: string, email: string, mobile: string, password: string): Promise<void>;
    rejectDeposit(token: string, requestId: string): Promise<void>;
    rejectWithdrawal(token: string, requestId: string): Promise<void>;
    removeFromWatchlist(token: string, symbol: string): Promise<void>;
    requestDeposit(token: string, amount: number): Promise<string>;
    requestWithdrawal(token: string, amount: number, withdrawalMethod: WithdrawalMethod, upiId: string | null, bankName: string | null, accountNumber: string | null, ifscCode: string | null): Promise<string>;
    setPaymentSettings(token: string, upiId: string, qrCodeData: string, bankAccountHolder: string, bankName: string, bankAccountNumber: string, bankIfsc: string): Promise<void>;
    submitDepositUtr(token: string, requestId: string, utrNumber: string): Promise<void>;
    updateAppSettings(token: string, termsText: string, privacyText: string, stockGainColor: string, stockLossColor: string): Promise<void>;
    updateInstrumentPrice(update: InstrumentUpdate): Promise<void>;
}
import type { Category as _Category, CreditCodeStatus as _CreditCodeStatus, CreditCodeV2 as _CreditCodeV2, DepositRequestV2 as _DepositRequestV2, DepositStatus as _DepositStatus, Instrument as _Instrument, OrderStatus as _OrderStatus, OrderType as _OrderType, OrderV2 as _OrderV2, PaymentSettingsV2 as _PaymentSettingsV2, PositionSummary as _PositionSummary, Side as _Side, Time as _Time, TradeType as _TradeType, User as _User, WithdrawalMethod as _WithdrawalMethod, WithdrawalRequestV2 as _WithdrawalRequestV2, WithdrawalStatus as _WithdrawalStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addToWatchlist(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addToWatchlist(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToWatchlist(arg0, arg1);
            return result;
        }
    }
    async adjustUserBalance(arg0: string, arg1: string, arg2: number, arg3: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adjustUserBalance(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adjustUserBalance(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async adminClosePosition(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminClosePosition(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminClosePosition(arg0, arg1, arg2);
            return result;
        }
    }
    async adminEditPosition(arg0: string, arg1: string, arg2: string, arg3: number, arg4: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminEditPosition(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminEditPosition(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async adminResetPassword(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminResetPassword(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminResetPassword(arg0, arg1, arg2);
            return result;
        }
    }
    async approveDeposit(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveDeposit(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveDeposit(arg0, arg1);
            return result;
        }
    }
    async approveWithdrawal(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveWithdrawal(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveWithdrawal(arg0, arg1);
            return result;
        }
    }
    async authenticate(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.authenticate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.authenticate(arg0);
            return result;
        }
    }
    async authenticateAdmin(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.authenticateAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.authenticateAdmin(arg0);
            return result;
        }
    }
    async closePosition(arg0: string, arg1: string, arg2: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.closePosition(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.closePosition(arg0, arg1, arg2);
            return result;
        }
    }
    async createCreditCode(arg0: string, arg1: string, arg2: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createCreditCode(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCreditCode(arg0, arg1, arg2);
            return result;
        }
    }
    async createInstrument(arg0: string, arg1: string, arg2: Category, arg3: number, arg4: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createInstrument(arg0, arg1, to_candid_Category_n1(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInstrument(arg0, arg1, to_candid_Category_n1(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
            return result;
        }
    }
    async deleteCreditCode(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCreditCode(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCreditCode(arg0, arg1);
            return result;
        }
    }
    async deleteInstrument(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInstrument(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInstrument(arg0);
            return result;
        }
    }
    async deposit(arg0: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deposit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deposit(arg0);
            return result;
        }
    }
    async getAdminStats(arg0: string): Promise<AdminStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminStats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminStats(arg0);
            return result;
        }
    }
    async getAllCreditCodes(arg0: string): Promise<Array<CreditCodeV2>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCreditCodes(arg0);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCreditCodes(arg0);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllDepositRequests(arg0: string): Promise<Array<DepositRequestV2>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDepositRequests(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDepositRequests(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllInstruments(): Promise<Array<Instrument>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInstruments();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInstruments();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllOrders(arg0: string): Promise<Array<OrderV2>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOrders(arg0);
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOrders(arg0);
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPositions(arg0: string): Promise<Array<[string, Array<PositionSummary>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPositions(arg0);
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPositions(arg0);
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsers(arg0: string): Promise<Array<[string, User]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers(arg0);
            return result;
        }
    }
    async getAllWithdrawalRequests(arg0: string): Promise<Array<WithdrawalRequestV2>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWithdrawalRequests(arg0);
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWithdrawalRequests(arg0);
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAppSettings(): Promise<AppSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppSettings();
            return result;
        }
    }
    async getAvailableBalance(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableBalance();
            return result;
        }
    }
    async getAvailableBalanceByToken(arg0: string): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableBalanceByToken(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableBalanceByToken(arg0);
            return result;
        }
    }
    async getDepositRequests(arg0: string): Promise<Array<DepositRequestV2>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDepositRequests(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDepositRequests(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInstrumentsByCategory(arg0: Category): Promise<Array<Instrument>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInstrumentsByCategory(to_candid_Category_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInstrumentsByCategory(to_candid_Category_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOpenPositions(arg0: string): Promise<Array<PositionSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOpenPositions(arg0);
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOpenPositions(arg0);
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrders(arg0: string): Promise<Array<OrderV2>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrders(arg0);
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrders(arg0);
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPaymentSettings(): Promise<PaymentSettingsV2 | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentSettings();
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentSettings();
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPortfolioSummary(arg0: string): Promise<PortfolioSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getPortfolioSummary(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPortfolioSummary(arg0);
            return result;
        }
    }
    async getProfileByToken(arg0: string): Promise<User> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfileByToken(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfileByToken(arg0);
            return result;
        }
    }
    async getSessionFull(arg0: string): Promise<[User, boolean] | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSessionFull(arg0);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSessionFull(arg0);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserByToken(arg0: string): Promise<[Principal, User]> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserByToken(arg0);
                return [
                    result[0],
                    result[1]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserByToken(arg0);
            return [
                result[0],
                result[1]
            ];
        }
    }
    async getUserProfile(): Promise<User> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile();
            return result;
        }
    }
    async getUserProfileByToken(arg0: string): Promise<User> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfileByToken(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfileByToken(arg0);
            return result;
        }
    }
    async getWatchlist(arg0: string): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWatchlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWatchlist(arg0);
            return result;
        }
    }
    async getWithdrawalRequests(arg0: string): Promise<Array<WithdrawalRequestV2>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWithdrawalRequests(arg0);
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWithdrawalRequests(arg0);
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async isAdminByToken(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdminByToken(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdminByToken(arg0);
            return result;
        }
    }
    async isAdminUser(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdminUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdminUser(arg0);
            return result;
        }
    }
    async loginFull(arg0: string, arg1: string): Promise<[string, User, boolean]> {
        if (this.processError) {
            try {
                const result = await this.actor.loginFull(arg0, arg1);
                return [
                    result[0],
                    result[1],
                    result[2]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginFull(arg0, arg1);
            return [
                result[0],
                result[1],
                result[2]
            ];
        }
    }
    async loginWithPassword(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.loginWithPassword(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginWithPassword(arg0, arg1);
            return result;
        }
    }
    async logoutByToken(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logoutByToken(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logoutByToken(arg0);
            return result;
        }
    }
    async placeOrder(arg0: string, arg1: string, arg2: number, arg3: number, arg4: OrderType, arg5: TradeType, arg6: Side): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrder(arg0, arg1, arg2, arg3, to_candid_OrderType_n44(this._uploadFile, this._downloadFile, arg4), to_candid_TradeType_n46(this._uploadFile, this._downloadFile, arg5), to_candid_Side_n48(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrder(arg0, arg1, arg2, arg3, to_candid_OrderType_n44(this._uploadFile, this._downloadFile, arg4), to_candid_TradeType_n46(this._uploadFile, this._downloadFile, arg5), to_candid_Side_n48(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async redeemCreditCode(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.redeemCreditCode(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.redeemCreditCode(arg0, arg1);
            return result;
        }
    }
    async registerUser(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, arg1, arg2);
            return result;
        }
    }
    async registerUserWithPassword(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUserWithPassword(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUserWithPassword(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async rejectDeposit(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectDeposit(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectDeposit(arg0, arg1);
            return result;
        }
    }
    async rejectWithdrawal(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectWithdrawal(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectWithdrawal(arg0, arg1);
            return result;
        }
    }
    async removeFromWatchlist(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromWatchlist(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromWatchlist(arg0, arg1);
            return result;
        }
    }
    async requestDeposit(arg0: string, arg1: number): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.requestDeposit(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestDeposit(arg0, arg1);
            return result;
        }
    }
    async requestWithdrawal(arg0: string, arg1: number, arg2: WithdrawalMethod, arg3: string | null, arg4: string | null, arg5: string | null, arg6: string | null): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.requestWithdrawal(arg0, arg1, to_candid_WithdrawalMethod_n50(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n52(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n52(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n52(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n52(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestWithdrawal(arg0, arg1, to_candid_WithdrawalMethod_n50(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n52(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n52(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n52(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n52(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async setPaymentSettings(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setPaymentSettings(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPaymentSettings(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async submitDepositUtr(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitDepositUtr(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitDepositUtr(arg0, arg1, arg2);
            return result;
        }
    }
    async updateAppSettings(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAppSettings(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAppSettings(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateInstrumentPrice(arg0: InstrumentUpdate): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInstrumentPrice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInstrumentPrice(arg0);
            return result;
        }
    }
}
function from_candid_Category_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_CreditCodeStatus_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CreditCodeStatus): CreditCodeStatus {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_CreditCodeV2_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CreditCodeV2): CreditCodeV2 {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_DepositRequestV2_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DepositRequestV2): DepositRequestV2 {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_DepositStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DepositStatus): DepositStatus {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Instrument_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Instrument): Instrument {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_OrderType_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderType): OrderType {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_OrderV2_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderV2): OrderV2 {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_PositionSummary_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PositionSummary): PositionSummary {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_Side_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Side): Side {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_TradeType_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TradeType): TradeType {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_WithdrawalMethod_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WithdrawalMethod): WithdrawalMethod {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid_WithdrawalRequestV2_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WithdrawalRequestV2): WithdrawalRequestV2 {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_WithdrawalStatus_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WithdrawalStatus): WithdrawalStatus {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PaymentSettingsV2]): PaymentSettingsV2 | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [[_User, boolean]]): [User, boolean] | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _DepositStatus;
    userEmail: string;
    utrNumber: [] | [string];
    amount: number;
    requestTime: _Time;
}): {
    id: string;
    status: DepositStatus;
    userEmail: string;
    utrNumber?: string;
    amount: number;
    requestTime: Time;
} {
    return {
        id: value.id,
        status: from_candid_DepositStatus_n13(_uploadFile, _downloadFile, value.status),
        userEmail: value.userEmail,
        utrNumber: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.utrNumber)),
        amount: value.amount,
        requestTime: value.requestTime
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    currentPrice: number;
    name: string;
    previousClose: number;
    priceChangePercent: number;
    category: _Category;
    symbol: string;
}): {
    currentPrice: number;
    name: string;
    previousClose: number;
    priceChangePercent: number;
    category: Category;
    symbol: string;
} {
    return {
        currentPrice: value.currentPrice,
        name: value.name,
        previousClose: value.previousClose,
        priceChangePercent: value.priceChangePercent,
        category: from_candid_Category_n18(_uploadFile, _downloadFile, value.category),
        symbol: value.symbol
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _OrderStatus;
    userEmail: string;
    tradeType: _TradeType;
    side: _Side;
    orderType: _OrderType;
    marginUsed: number;
    timestamp: _Time;
    quantity: number;
    price: number;
    symbol: string;
}): {
    id: string;
    status: OrderStatus;
    userEmail: string;
    tradeType: TradeType;
    side: Side;
    orderType: OrderType;
    marginUsed: number;
    timestamp: Time;
    quantity: number;
    price: number;
    symbol: string;
} {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n23(_uploadFile, _downloadFile, value.status),
        userEmail: value.userEmail,
        tradeType: from_candid_TradeType_n25(_uploadFile, _downloadFile, value.tradeType),
        side: from_candid_Side_n27(_uploadFile, _downloadFile, value.side),
        orderType: from_candid_OrderType_n29(_uploadFile, _downloadFile, value.orderType),
        marginUsed: value.marginUsed,
        timestamp: value.timestamp,
        quantity: value.quantity,
        price: value.price,
        symbol: value.symbol
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tradeType: _TradeType;
    marginUsed: number;
    quantity: number;
    unrealizedPnL: number;
    avgBuyPrice: number;
    symbol: string;
}): {
    tradeType: TradeType;
    marginUsed: number;
    quantity: number;
    unrealizedPnL: number;
    avgBuyPrice: number;
    symbol: string;
} {
    return {
        tradeType: from_candid_TradeType_n25(_uploadFile, _downloadFile, value.tradeType),
        marginUsed: value.marginUsed,
        quantity: value.quantity,
        unrealizedPnL: value.unrealizedPnL,
        avgBuyPrice: value.avgBuyPrice,
        symbol: value.symbol
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _WithdrawalStatus;
    userEmail: string;
    ifscCode: [] | [string];
    bankName: [] | [string];
    upiId: [] | [string];
    withdrawalMethod: _WithdrawalMethod;
    accountNumber: [] | [string];
    amount: number;
    requestTime: _Time;
}): {
    id: string;
    status: WithdrawalStatus;
    userEmail: string;
    ifscCode?: string;
    bankName?: string;
    upiId?: string;
    withdrawalMethod: WithdrawalMethod;
    accountNumber?: string;
    amount: number;
    requestTime: Time;
} {
    return {
        id: value.id,
        status: from_candid_WithdrawalStatus_n39(_uploadFile, _downloadFile, value.status),
        userEmail: value.userEmail,
        ifscCode: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.ifscCode)),
        bankName: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.bankName)),
        upiId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.upiId)),
        withdrawalMethod: from_candid_WithdrawalMethod_n40(_uploadFile, _downloadFile, value.withdrawalMethod),
        accountNumber: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.accountNumber)),
        amount: value.amount,
        requestTime: value.requestTime
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    redeemedAt: [] | [_Time];
    redeemedBy: [] | [string];
    status: _CreditCodeStatus;
    code: string;
    createdAt: _Time;
    amount: number;
}): {
    redeemedAt?: Time;
    redeemedBy?: string;
    status: CreditCodeStatus;
    code: string;
    createdAt: Time;
    amount: number;
} {
    return {
        redeemedAt: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.redeemedAt)),
        redeemedBy: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.redeemedBy)),
        status: from_candid_CreditCodeStatus_n8(_uploadFile, _downloadFile, value.status),
        code: value.code,
        createdAt: value.createdAt,
        amount: value.amount
    };
}
function from_candid_tuple_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, Array<_PositionSummary>]): [string, Array<PositionSummary>] {
    return [
        value[0],
        from_candid_vec_n33(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): DepositStatus {
    return "pending" in value ? DepositStatus.pending : "approved" in value ? DepositStatus.approved : "rejected" in value ? DepositStatus.rejected : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    forex: null;
} | {
    stock: null;
} | {
    crypto: null;
} | {
    commodity: null;
}): Category {
    return "forex" in value ? Category.forex : "stock" in value ? Category.stock : "crypto" in value ? Category.crypto : "commodity" in value ? Category.commodity : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    rejected: null;
} | {
    executed: null;
}): OrderStatus {
    return "cancelled" in value ? OrderStatus.cancelled : "pending" in value ? OrderStatus.pending : "rejected" in value ? OrderStatus.rejected : "executed" in value ? OrderStatus.executed : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    carryForward: null;
} | {
    intraday: null;
}): TradeType {
    return "carryForward" in value ? TradeType.carryForward : "intraday" in value ? TradeType.intraday : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    buy: null;
} | {
    sell: null;
}): Side {
    return "buy" in value ? Side.buy : "sell" in value ? Side.sell : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    limit: null;
} | {
    stopLoss: null;
} | {
    market: null;
}): OrderType {
    return "limit" in value ? OrderType.limit : "stopLoss" in value ? OrderType.stopLoss : "market" in value ? OrderType.market : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    upi: null;
} | {
    bank: null;
}): WithdrawalMethod {
    return "upi" in value ? WithdrawalMethod.upi : "bank" in value ? WithdrawalMethod.bank : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    redeemed: null;
}): CreditCodeStatus {
    return "active" in value ? CreditCodeStatus.active : "redeemed" in value ? CreditCodeStatus.redeemed : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DepositRequestV2>): Array<DepositRequestV2> {
    return value.map((x)=>from_candid_DepositRequestV2_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Instrument>): Array<Instrument> {
    return value.map((x)=>from_candid_Instrument_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OrderV2>): Array<OrderV2> {
    return value.map((x)=>from_candid_OrderV2_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CreditCodeV2>): Array<CreditCodeV2> {
    return value.map((x)=>from_candid_CreditCodeV2_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, Array<_PositionSummary>]>): Array<[string, Array<PositionSummary>]> {
    return value.map((x)=>from_candid_tuple_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PositionSummary>): Array<PositionSummary> {
    return value.map((x)=>from_candid_PositionSummary_n34(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WithdrawalRequestV2>): Array<WithdrawalRequestV2> {
    return value.map((x)=>from_candid_WithdrawalRequestV2_n37(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_OrderType_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderType): _OrderType {
    return to_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function to_candid_Side_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Side): _Side {
    return to_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function to_candid_TradeType_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradeType): _TradeType {
    return to_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function to_candid_WithdrawalMethod_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WithdrawalMethod): _WithdrawalMethod {
    return to_candid_variant_n51(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    forex: null;
} | {
    stock: null;
} | {
    crypto: null;
} | {
    commodity: null;
} {
    return value == Category.forex ? {
        forex: null
    } : value == Category.stock ? {
        stock: null
    } : value == Category.crypto ? {
        crypto: null
    } : value == Category.commodity ? {
        commodity: null
    } : value;
}
function to_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderType): {
    limit: null;
} | {
    stopLoss: null;
} | {
    market: null;
} {
    return value == OrderType.limit ? {
        limit: null
    } : value == OrderType.stopLoss ? {
        stopLoss: null
    } : value == OrderType.market ? {
        market: null
    } : value;
}
function to_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradeType): {
    carryForward: null;
} | {
    intraday: null;
} {
    return value == TradeType.carryForward ? {
        carryForward: null
    } : value == TradeType.intraday ? {
        intraday: null
    } : value;
}
function to_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Side): {
    buy: null;
} | {
    sell: null;
} {
    return value == Side.buy ? {
        buy: null
    } : value == Side.sell ? {
        sell: null
    } : value;
}
function to_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WithdrawalMethod): {
    upi: null;
} | {
    bank: null;
} {
    return value == WithdrawalMethod.upi ? {
        upi: null
    } : value == WithdrawalMethod.bank ? {
        bank: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
